### DISCUSSION TITLE
Example of NATS with externalAccess

### DISCUSSION THREAD

**Discussion by andretadeu** [nats-io/k8s#566] [Q&A]
Hi,

I am trying to configure NATS for external access by following the documentation in [Setting up External Access](https://docs.nats.io/running-a-nats-service/nats-kubernetes/helm-charts#setting-up-external-access), however I am not having much success on it. I tried both without load balancer or with it.

values.yaml without load balancer configurations:
```yaml
nats:
  bootconfig:
    image: natsio/nats-boot-config:latest
    pullPolicy: IfNotPresent
  nats:
    enabled: true
    externalAccess: true
    advertise: true
    serviceAccount:
      name: "nats-server"

    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 2Gi
```

values.yaml with load balancer configurations:
```yaml
nats:
  bootconfig:
    image: natsio/nats-boot-config:latest
    pullPolicy: IfNotPresent
  nats:
    enabled: true
    externalAccess: true
    advertise: true
    serviceAccount:
      name: "nats-server"

    jetstream:
      enabled: true
      memStorage:
        enabled: true
        size: 2Gi
  cluster:
    enabled: true
    noAdvertise: true
  leafnodes:
    enabled: true
    noAdvertise: true
  natsbox:
    image: natsio/nats-box:latest
    enabled: true
```
But I am always having the following issue:

```
NAME                            READY   STATUS                  RESTARTS        AGE
inf-nats-box-5fccdd8f55-glczt   1/1     Running                 0               19m
mongodb-0                       1/1     Running                 0               19m
mongodb-1                       1/1     Running                 0               19m
mongodb-2                       1/1     Running                 0               19m
inf-nats-0                      0/3     Init:CrashLoopBackOff   8 (3m19s ago)   19m
```

and 

```
[<redacted> ~]$ microk8s kubectl -n ipm-inf logs inf-nats-0
Defaulted container "nats" out of: nats, reloader, metrics, bootconfig (init)
Error from server (BadRequest): container "nats" in pod "inf-nats-0" is waiting to start: PodInitializing
```

What is missing in the configurations here?

Edit 1: redacted user and host
