### DISCUSSION TITLE
Cluster Authorization from Secret

### DISCUSSION THREAD

**Discussion by joelp172** [nats-io/k8s#833] [Q&A] [answered]
I am trying to deploy NATS on multiple k8s clusters, which I have done successfully. I want to add authorization config to each cluster, however I cant find a way to specify a username and password in the [config.cluster.authorization](https://github.com/nats-io/k8s/blob/664ab971fa43f9418999cd942adab44e4068518a/helm/charts/nats/values.yaml#L61) value securely i.e. from a Secret. 

Does this functionality not exists or have i missed something? Is the only way to specify these values in plain text when deploying using helm?

**Comment by caleblloyd** [comment, marked as answer]
It involves some templating.  In NATS config, user/pass route auth has to be [specified as part of the URL](https://docs.nats.io/running-a-nats-service/configuration/clustering/cluster_config) for `cluster.routes`:

> A list of other servers (URLs) to cluster with. Self-routes are ignored. Should authentication via token or username/password be required, specify them as part of the URL.

I don't think NATS config can do string interpolation with variables to build those URLs.  So they'd have to be built in Environment Variables.  Try this:

```yaml
config:
  cluster:
    enabled: true
    routeURLs:
      user: foo
      password: << $CLUSTER_AUTH >>
    merge:
      routes:
        $tplYaml: |
          {{- range $i, $_ := until (int $.Values.config.cluster.replicas) }}
          - << $ROUTE_{{ $i }} >>
          {{- end }}

container:
  env:
    CLUSTER_AUTH:
       valueFrom:
         secretKeyRef:
           name: secret-name
           key: secret-key
    ROUTES:
      $tplYamlSpread: |
        {{- range $i, $_ := until (int $.Values.config.cluster.replicas) }}
        ROUTE_{{ $i }}: {{ printf "nats://%s:$(CLUSTER_AUTH)@%s-%d.%s:%d" $.Values.config.cluster.routeURLs.user $.Values.statefulSet.name $i $.Values.headlessService.name (int $.Values.config.cluster.port) }}
        {{- end }}

```
