### DISCUSSION TITLE
How do i add Node Affinity in values.yaml file

### DISCUSSION THREAD

**Discussion by YashasAnand** [nats-io/k8s#947] [Q&A]
Can someone pls tell me where do i add node affinity as i dont see these sections in values.yaml file.

**Comment by apena-pmy** [comment]
Hi @YashasAnand !
If you want to add affinity to nats chart template, this is how we add `podAntiAffinity`:
```
podTemplate:
  merge:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - nats
                topologyKey: kubernetes.io/hostname
              weight: 1
```

If you want for other template, please share wich one so anyone can help you.

**Comment by pbennett** [comment]
If using the nats helm chart, you can use the recommended settings:
```
config:
  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
```
It's listed in jetstream 3 node cluster example.
