### DISCUSSION TITLE
How to specify Tolerations, Affinity or Node Selector in NATS Helm Chart?

### DISCUSSION THREAD

**Discussion by jmcorne** [nats-io/k8s#960] [Q&A] [answered]
I read the source code of NATS chart (v1.2.9) and I didn't see any values to configure those node selectors?

ThX

**Comment by z0mbix** [comment, marked as answer]
You can use:

```yaml
podTemplate:
  merge:
    spec:
      nodeSelector:
        workload: nats
```
