### DISCUSSION TITLE
Helm Chart Config merge directive

### DISCUSSION THREAD

**Discussion by Demmyart** [nats-io/k8s#962] [Q&A]
Hello, guys can not get a working documented feature

```   
config:
   merge:
     max_payload: << 8MB >>
  jetstream:
      enabled: true
```

but my nats config map does not affected and **_max_payload_** field is not included

helm chart version: 2.10.12
