### ISSUE TITLE
NATS Helm: merge for resource limits is ignored

### ISSUE THREAD

**Issue by JM322** [nats-io/k8s#1002]
### What version were you using?

Application Version: 2.11.3
Chart Version: 1.3.6

### What environment was the server running in?

Kubernetes

### Is this defect reproducible?

1. Create a Chart.yaml
```yaml
apiVersion: v2
name: nats
description: A Helm chart for CPS deployment of a NATS Leaf Node
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: nats
    version: 1.3.6
    repository: "https://nats-io.github.io/k8s/helm/charts/"
```
2. Get the default values from [ArtifactHub](https://artifacthub.io/packages/helm/nats/nats) and add resource limits in the merge section as described in the [documentation](https://artifacthub.io/packages/helm/nats/nats#nats-container-resources):
```yaml
container:
  env:
    # Different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    # Should be ~80% of memory limit
    GOMEMLIMIT: 6GiB
  merge:
    # Recommended minimum: at least 2 CPU cores and 8Gi memory for production JetStream clusters
    resources:
      requests:
        cpu: "2"
        memory: 8Gi
      limits:
        cpu: "2"
        memory: 8Gi
```
4. Apply helm template with the modified values.yaml: `helm template nats . --namespace nats --debug  --values values.yaml`

### Given the capability you are leveraging, describe your expectation?

Resource limits should be applied to the nats containers.

### Given the expectation, what is the defect you are observing?

No resource limits are present in the created Kubernetes manifests.

**Comment by alexbozhenko** [comment]
@samuelattwood do you happen to have example how to set those values?

**Comment by samuelattwood** [comment]
@JM322 You are setting this correctly for the NATS chart, the problem is that you are sub-charting the NATS chart so you will need to specify the chart name header prior to the NATS config.

```
nats:
  container:
    env:
      # Different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
      # Should be ~80% of memory limit
      GOMEMLIMIT: 6GiB
    merge:
      # Recommended minimum: at least 2 CPU cores and 8Gi memory for production JetStream clusters
      resources:
        requests:
          cpu: "2"
          memory: 8Gi
        limits:
          cpu: "2"
          memory: 8Gi
```
