### ISSUE TITLE
Grafana unreachable because targetPorts do not match

### ISSUE THREAD

**Issue by jason-magnetic-io** [nats-io/k8s#11]
The `targetPort` for the `grafana` Service doesn't match the `targetPort` for the container in the `nats-surveyor-grafana` Deployment, e.g. "web" versus "wep"
```
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
...
  ports:
  - name: web
    # nodePort: 30300
    port: 3000
    protocol: TCP
    targetPort: web
```
versus
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-surveyor-grafana
...
        ports:
        - containerPort: 3000
          name: wep
```
