### ISSUE TITLE
Clustered STAN is not working with sql db

### ISSUE THREAD

**Issue by sergeyshaykhullin** [nats-io/k8s#120]
Hello, i am using NATS x3, clustered STAN x3 and PostgreSQL deployed by Helm

- Nonclustered STAN with 1 replica is working fine
- Clustered STAN with 3 replicas is failing with
![image](https://user-images.githubusercontent.com/46970457/92960071-9cf6ea80-f475-11ea-9b6a-910c6ee9558f.png)

Also stan-0 has stan-0 cluster id, but stan-1 also has stan-0 id

My stan values.yaml template:

```yaml
stan:
  replicas: 3
  nats:
    url: nats://nats.nats:4222

store:
  type: sql

  limits:
    max_channels: 200
    # 5 GB
    max_bytes: 5368706371
    max_subs: 2000

  volume:
    enabled: false

  cluster:
    enabled: true

  sql:
    driver: postgres
    source: dbname={{ stan.postgresql.database }} user={{ stan.postgresql.username }} password={{ stan.postgresql.password }} host={{ stan.postgresql.host }} sslmode=disable
    initdb:
      enabled: true
    dbName: {{ stan.postgresql.database }}
    dbUser: {{ stan.postgresql.username }}
    dbPassword: {{ stan.postgresql.password }}
    dbHost: {{ stan.postgresql.host }}
    dbPort: {{ stan.postgresql.port }}
```

**Comment by wallyqs** [comment]
Hi, I think clustered stan will not work very well with db mode backend since it would mean to use 3 different DB instances.  I would recommend to try instead the FT mode:

```yaml
store:
  ft:
    group: stan
```
