### ISSUE TITLE
Update NATS_URL of nats-box according to the overridden release name

### ISSUE THREAD

**Issue by hpthai7** [nats-io/k8s#129]
Hi,

The name of resources coming from the NATS Helm chart can be overridden with the key `nameOverride` from `values.yaml`:

```yaml
# nats/templates/_helpers.tpl
{{/*
Expand the name of the chart.
*/}}
{{- define "nats.name" -}}
{{- default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}
```

Hence all resources instantiated from the Helm chart will get the overriding name.

However, the `NATS_URL` from the nats-box pod only refers to `.Release.Name`. When the chart name is overridden, the nats-box test is no longer working.

```yaml
# nats/templates/nats_box.yaml
  containers:
  - name: nats-box
    image: {{ .Values.natsbox.image }}
    imagePullPolicy: {{ .Values.natsbox.pullPolicy }}
    env:
    - name: NATS_URL
      value: {{ .Release.Name }}
```
