### ISSUE TITLE
[stan] Prevent enabling both ft and cluster mode

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#143]
It should prevent being able to activate both:

```yaml
stan:
  image: nats-streaming:alpine
  replicas: 3
store:
  type: file
  ft:
    group: stan-group
  volume:
    enabled: true
    mount: /data/stan
    persistentVolumeClaim:
      claimName: stan-efs
  cluster:
    enabled: true
    logPath: /data/stan/log
```
