### ISSUE TITLE
[helm/stan] Cannot set limits to unlimited values

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#162]
Zero values become ignored so means that cannot disable limits for max_channels etc... meaning that this wouldn't work

```yaml
store:
  type: file
  ft:
    group: ns
  limits: 
    max_channels: 0
```
