### ISSUE TITLE
nats chart should support setting the service.spec.type

### ISSUE THREAD

**Issue by benmathews** [nats-io/k8s#183]
The nats chart service template doesn't specify service.spec.type. Therefore, it defaults to ClusterIP. To expose the cluster to outside, I would like to have NodePort as an option.

**Comment by wallyqs** [comment]
Would it be good if the Helm charts are extended to create a NodePort via a toggle.  Here is an example to create one out of band as well:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nats-nodeport
  labels:
    app: nats
  annotations:
    external-dns.alpha.kubernetes.io/hostname: sfo.nats.chat
spec:
  type: NodePort
  selector:
    app: nats
  externalTrafficPolicy: Local
  ports:
  - name: client
    port: 4222
    nodePort: 30222
    targetPort: 4222
  - name: websocket
    port: 443
    nodePort: 30223
    targetPort: 443
```
