### ISSUE TITLE
How to specify storage class for stan volume persistent claim?

### ISSUE THREAD

**Issue by damir-manapov** [nats-io/k8s#19]

**Comment by matthewhartstonge** [comment]
Hi @damir-manapov,

You can do this using the [`simple-stan`](https://github.com/nats-io/k8s/blob/master/nats-streaming-server/simple-stan.yml) example as a template. You can then update the yaml spec to include the storage class you require.
See: https://github.com/nats-io/k8s/blob/master/nats-streaming-server/simple-stan.yml#L51-L60

### Clustering

For example:
```yaml
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: "Filesystem"
      resources:
        requests:
          storage: 1Gi
```

Would become:
```yaml
  volumeClaimTemplates:
  - metadata:
      name: stan-sts-vol
    spec:
      accessModes:
      - ReadWriteOnce
      volumeMode: "Filesystem"
      storageClassName: YOUR_STORAGE_CLASS_NAME
      resources:
        requests:
          storage: 1Gi
```

### Fault Tolerance Mode
If you are running in fault tolerance mode, (by tweaking the config) you would need to remove the [`volumeClaimTemplate`](https://github.com/nats-io/k8s/blob/master/nats-streaming-server/simple-stan.yml#L51-L60) and create a PVC that supports `ReadWriteMany` by itself:

```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stan-sts-vol
spec:
  storageClassName: YOUR_STORAGE_CLASS_NAME
  accessModes:
    - ReadWriteMany
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: 1Gi
```

And then bind that in via volumes at https://github.com/nats-io/k8s/blob/master/nats-streaming-server/simple-stan.yml#L77-L122:

```yaml
...
      # STAN Server
      containers:
        - name: stan
          image: nats-streaming:0.16.2
          ports:
            - containerPort: 8222
              name: monitor
            - containerPort: 7777
              name: metrics
          args:
            - "-sc"
            - "/etc/stan-config/stan.conf"

          # Required to be able to define an environment variable
          # that refers to other environment variables.  This env var
          # is later used as part of the configuration file.
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config-volume
              mountPath: /etc/stan-config
            - name: stan-sts-vol
              mountPath: /data/stan

          # Disable CPU limits.
          resources:
            requests:
              cpu: 0

          livenessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config-volume
          configMap:
            name: stan-config
        - name: stan-data-vol
          persistentVolumeClaim:
            claimName: stan-sts-vol
```

Fault Tolerance Spec all together:
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: stan-sts-vol
spec:
  storageClassName: YOUR_STORAGE_CLASS_NAME
  accessModes:
    - ReadWriteMany
  volumeMode: "Filesystem"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stan-config
data:
  stan.conf: |
    port: 4222
    http: 8222
    streaming {
     ns: "nats://nats:4222"
     id: stan
     store: file
     dir: /data/stan/store

     # Configure cluster to run in Fault Tolerance mode (no clustering).
     ft_group: stan-ft
    }
---
apiVersion: v1
kind: Service
metadata:
  name: stan
  labels:
    app: stan
spec:
  selector:
    app: stan
  clusterIP: None
  ports:
  - name: metrics
    port: 7777
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stan
  labels:
    app: stan
spec:
  selector:
    matchLabels:
      app: stan
  serviceName: stan
  replicas: 3
  template:
    metadata:
      labels:
        app: stan
    spec:
      # Prevent NATS Streaming pods running in same host.
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - stan
      # STAN Server
      containers:
      - name: stan
        image: nats-streaming:0.16.2
        ports:
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics
        args:
         - "-sc"
         - "/etc/stan-config/stan.conf"

        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - name: config-volume
            mountPath: /etc/stan-config
          - name: stan-sts-vol
            mountPath: /data/stan

        # Disable CPU limits.
        resources:
          requests:
            cpu: 0

        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: stan-config
      - name: stan-sts-vol
        persistentVolumeClaim:
          claimName: stan-sts-vol
```


Hope that helps!
