### ISSUE TITLE
helm chart for nats renders pod for natsbox

### ISSUE THREAD

**Issue by arturrez** [nats-io/k8s#194]
should it be deployment  with one pod ?
```
helm pull nats/nats --version 0.7.5
helm template --set natsbox.enabled=true ./nats-0.7.5.tgz | more
```

```
# Source: nats/templates/nats-box.yaml
apiVersion: v1
kind: Pod
metadata:
  name: RELEASE-NAME-box
  labels:
    app: RELEASE-NAME-box
    chart: nats-0.7.5
spec:
  volumes:

  containers:
  - name: nats-box
    image: synadia/nats-box:0.4.0
    imagePullPolicy: IfNotPresent
    env:
    - name: NATS_URL
      value: RELEASE-NAME
    command:
     - "tail"
     - "-f"
     - "/dev/null"
    volumeMounts:
```
