### ISSUE TITLE
parse error deploying with jetstream clustering

### ISSUE THREAD

**Issue by justinrush** [nats-io/k8s#219]
Trying to deploy using helm
```bash
helm upgrade --install --namespace nats nats nats/nats -f myvalues.yaml
```

and this is myvalues.yaml:
```yaml
nats:
  image: nats:2.1.9-alpine3.12
  externalAccess: true
  advertise: false
  jetstream:
    enabled: true
    memStorage:
      enabled: true
      size: 1Gi
    fileStorage:
      enabled: true
      size: 8Gi
      storageClassName: "myclass"
cluster:
  enabled: true
  replicas: 3
  noAdvertise: true
  name: "nats"
bootconfig:
  image: connecteverything/nats-boot-config:0.5.2
natsbox:
  image: synadia/nats-box:0.4.0
reloader:
  image: connecteverything/nats-server-config-reloader:0.6.0
exporter:
  enabled: true
  image: synadia/prometheus-nats-exporter:0.5.0
auth:
  enabled: false
```

I get this in the log of the first nats pod that gets deployed:

```
nats nats-server: Parse error on line 17: 'Expected a map value terminator "," or a map terminator "}", but got 'i' instead.'
nats stream closed
reloader 2021/04/08 14:58:07 Starting NATS Server Reloader v0.6.0+git
reloader 2021/04/08 14:58:07 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2021/04/08 14:58:09 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2021/04/08 14:58:11 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2021/04/08 14:58:13 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2021/04/08 14:58:15 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2021/04/08 14:58:17 Error: open /var/run/nats/nats.pid: no such file or directory
reloader Error: Too many errors attempting to find server process 
```
