### ISSUE TITLE
helm: 'tolerations' spec attributes are missing in the nats helm chart

### ISSUE THREAD

**Issue by carlosrmendes** [nats-io/k8s#231]

**Comment by LarsBingBong** [comment]
Is this being looked at?

**Comment by mprimeaux** [comment]
I think this can be closed based on [this](https://github.com/nats-io/k8s/blob/c7fa7cd0fc622a974ed346c6d72a28b97118f668/helm/charts/nats/templates/statefulset.yaml#L68).

**Comment by anapsix** [comment]
looks like the latest chart version 1.1.0 is missing `tolerations` (and `nodeSelector` for that matter) in its [`stateful-set.yaml`](https://github.com/nats-io/k8s/blob/nats-1.1.0/helm/charts/nats/files/stateful-set/stateful-set.yaml)

**Comment by caleblloyd** [comment]
@anapsix you can add those with the appropriate `merge` keys under `podTemplate`:

```yaml
podTemplate:
  merge:
    spec:
      nodeSelector: // your node selector
      tolerations: // your tolerations
```

That's how the 1.x chart works for anything not specefically defined in the `values.yaml`

The [README](https://github.com/nats-io/k8s/blob/main/helm/charts/nats/README.md) has some good docs and examples
