### ISSUE TITLE
helm stan:  Backup with persistence type "File" doesn't work

### ISSUE THREAD

**Issue by onyxet** [nats-io/k8s#233]
Hi all.

I'm trying to provision nats streaming service with stan chart version `0.7.4` and my current persistance settings are:

```
store:
  backup:
    enabled: true
    sleepTime: 150
    s3Path: "s3://bucket_name/stan-nebula-backups"
    credentialsSecretName: "stan-credentials"
  cluster:
    enabled: true
  type: file
```
In default `values` there is a backup script which uses `aws-cli` for copying `.bak` files which should be created via `backupScript` content but in default values there is only:

```
    backupScript: |-
      #!/bin/sh
      echo backup
```

which does nothing.

It's quite confusing configuration and seems that default values should contain proper backup script
