### ISSUE TITLE
nats-server: variable reference for 'CLUSTER_ADVERTISE' on line 22 could not be parsed

### ISSUE THREAD

**Issue by samstride** [nats-io/k8s#239]
Hi,

I have installed `nats-server` using the helm chart:

```
helm install nats-server nats/nats --namespace=nats \
    --set exporter.enabled=false \
    --set cluster.enabled=true \
    --set cluster.replicas=3 \
    -f nats-affinity.yaml
    
helm list

NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                                   APP VERSION
nats-nfs-client nats            1               2021-05-11 15:06:48.166794 +1200 NZST   deployed        nfs-subdir-external-provisioner-4.0.10  4.0.2      
nats-server     nats            1               2021-05-21 16:28:52.819114 +1200 NZST   deployed        nats-0.8.0                              2.2.3      
stan-server     nats            2               2021-05-21 12:13:24.229234 +1200 NZST   deployed        stan-0.8.0                              0.21.2  
```

When a `nats-server` pod is restarted (auto heal or manually), I am running into the following error:

```
kubectl get pods

NAME                                                              READY   STATUS             RESTARTS   AGE
nats-nfs-client-nfs-subdir-external-provisioner-5576875c48vchpk   1/1     Running            0          3d
nats-server-0                                                     2/2     Running            0          34m
nats-server-1                                                     2/2     Running            0          34m
nats-server-2                                                     0/2     CrashLoopBackOff   11         6m21s
nats-server-box-7b7755fcdd-6dr6f                                  1/1     Running            0          34m
stan-server-0                                                     2/2     Running            0          4h49m
stan-server-1                                                     2/2     Running            0          4h49m
stan-server-2                                                     2/2     Running            0          4h50m

kubectl logs -f nats-server-2 -c nats

nats-server: variable reference for 'CLUSTER_ADVERTISE' on line 22 could not be parsed: variable reference for '(POD_NAME).nats-server.$(POD_NAMESPACE).svc' on line 1 can not be found
```

Did I miss any step during the install or is this a bug?

Cheers.

**Comment by wallyqs** [comment]
This would be an unexpected bug, this is being defined here: https://github.com/nats-io/k8s/blob/7e7e05481c244ca5aa64c89777499ea9c442d3b8/helm/charts/nats/templates/statefulset.yaml#L240-L250
What version of k8s are you using?

**Comment by samstride** [comment]
@wallyqs 

Rancher v1.18.18

**Comment by arjenvdhave** [comment]
We are running in the same issue
Rancher: 2.5.8
K8s: v1.20.8

It looks like it is missing a $ if you look at the error message:
`variable reference for '(POD_NAME).nats-server.$(POD_NAMESPACE).svc'`

however the env var is:
$(POD_NAME).nats-server.$(POD_NAMESPACE).svc

so why it is "loosing" a $ after you restart a pod

**Comment by arjenvdhave** [comment]
@wallyqs
What is the exact usecase for `cluster_advertise: $CLUSTER_ADVERTISE` in the config map?
if i remove this from the configmap my cluster seems to redeploy without issues

**Comment by arjenvdhave** [comment]
Another update
after changing the terminationGracePeriodSeconds the cluster is able te redeploy ???

`terminationGracePeriodSeconds: 5`

**Comment by umaralam48** [comment]
@wallyqs facing a similar issue. Any solutions for this?

**Comment by wallyqs** [comment]
@umaralam48 could you share the resulting configmap from when this happens? I think one option would be to modify this to disable advertisements when `noAdvertise` is enabled: https://github.com/nats-io/k8s/blob/050da3e16b2ba56671da88a7da1c388a400c3a7a/nats-server/nats-server-plain.yml#L24

**Comment by umaralam48** [comment]
I think I found the issue. This is related to the order of environment variables in the statefulset spec.

Spec for the nats container in the statefulset - 

```yaml
 nats:
    Image:       nats:2.6.1-alpine
    Ports:       4222/TCP, 7422/TCP, 7522/TCP, 6222/TCP, 8222/TCP, 7777/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      nats-server
      --config
      /etc/nats-config/nats.conf
    Liveness:   http-get http://:8222/ delay=10s timeout=5s period=10s #success=1 #failure=3
    Readiness:  http-get http://:8222/ delay=10s timeout=5s period=10s #success=1 #failure=3
    Environment:
      CLUSTER_ADVERTISE:  $(POD_NAME).nats.$(POD_NAMESPACE).svc.cluster.prod
      POD_NAME:            (v1:metadata.name)
      POD_NAMESPACE:       (v1:metadata.namespace)
    Mounts:
      /data/ from nats-js-pvc (rw)
      /etc/nats-certs/cluster/nats-server-tls from nats-server-tls-cluster-volume (rw)
      /etc/nats-config from config-volume (rw)
      /var/run/nats from pid (rw)
```
In my case, I am applying a patch on the statefulset to change the `CLUSTER_ADVERTISE` environment variable which is then getting pushed to the top of the env list.

See - https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/#define-an-environment-dependent-variable-for-a-container
