### ISSUE TITLE
Installing a JetStream Cluster does not compute proper clusterRoutes in configMap

### ISSUE THREAD

**Issue by stephane-moreau** [nats-io/k8s#240]
Hello,

I tried to install a JetStream cluster using the following command line on a local k3s cluster (4 nodes)
 helm -n events install events -f install.yml nats/nats

content of install..yml
```yaml
nats:
  image: nats:2.2.5-alpine3.13
  jetstream:
    enabled: true
    fileStorage:
      enabled: true
      storageClassName: local-path

cluster:
  enabled: true
  noAdvertise: true
  replica: 3 

leafnodes:
  enabled: true
  noAdvertise: true

natsbox:
  enabled: true
```

doing so the everything starts, the pods are created and running  you can connect to the nats server but cannot start a JetStream context

Loking at the logs of the nats container:
```log
7] 2021/05/21 14:22:56.010346 [INF] Listening for route connections on 0.0.0.0:6222
[7] 2021/05/21 14:22:56.015511 [ERR] Error trying to connect to route (attempt 1): lookup for host "events-1.events.events.svc": lookup events-1.events.events.svc on 10.63.0.10:53: no such host
[7] 2021/05/21 14:22:56.015959 [ERR] Error trying to connect to route (attempt 1): lookup for host events-2.events.events.svc": lookup events-2.events.events.svc on 10.63.0.10:53: no such host
[7] 2021/05/21 14:22:56.016202 [ERR] Error trying to connect to route (attempt 1): lookup for host "events-0.events.events.svc": lookup events-0.events.events.svc on 10.63.0.10:53: no such host
```

The configMap contains list of cluster routes
```yaml
   ###################################
    #                                 #
    # NATS Full Mesh Clustering Setup #
    #                                 #
    ###################################
    cluster {
      port: 6222
      name: imo-events-nats

      routes = [
        nats://events-0.events.events.svc:6222,nats://events-1.events.events.svc:6222,nats://events-2.events.events.svc:6222,
      ]
      cluster_advertise: $CLUSTER_ADVERTISE
      no_advertise: true

      connect_retries: 30
    }
```

the generated StatefulSet contains the floownig
```yaml
---
# Source: nats/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: events-nats
  labels:
    helm.sh/chart: nats-0.8.0
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: events
    app.kubernetes.io/version: "2.2.3"
    app.kubernetes.io/managed-by: Helm
```

Manually changing cluster routes to match the name of the statefull set instead of the realease name did fix the JetStreamContext creation issue
```yaml
      routes = [
        nats://events-nats-0.events-nats.events.svc:6222,nats://events-nats-1.events-nats.events.svc:6222,nats://events-nats-2.events-nats.events.svc:6222,
      ]
```

I could etiher work around this be using the nameOveride and fullnameOverride

but here is a quick "patch" that look like working for me 
```diff
diff --git a/helm/charts/nats/templates/_helpers.tpl b/helm/charts/nats/templates/_helpers.tpl
index 9a55091..d8d01d2 100644
--- a/helm/charts/nats/templates/_helpers.tpl
+++ b/helm/charts/nats/templates/_helpers.tpl
@@ -58,7 +58,7 @@ Return the proper NATS image name
 Return the NATS cluster routes.
 */}}
 {{- define "nats.clusterRoutes" -}}
-{{- $name := default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
+{{- $name := (include "nats.fullname" . ) -}}
 {{- range $i, $e := until (.Values.cluster.replicas | int) -}}
 {{- printf "nats://%s-%d.%s.%s.svc:6222," $name $i $name $.Release.Namespace -}}
 {{- end -}}
```

Don't hesitate to let me know if you need me to create / submit a PR with this or if I should do it another way round

Thanks
Stephane MOREAU
