### ISSUE TITLE
L4 loadbalancer stopped working after upgrade to chart version 0.8.0

### ISSUE THREAD

**Issue by samstride** [nats-io/k8s#243]
Hi,

We upgraded from `v0.7.4` to `v0.8.0` and our L4 load balancer stopped working.

Rolling back to `v0.7.4` fixed it.

Here is the L4 balancer config we are using on `Rancher v 1.18.18`

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: nats
  labels:
    app: nats-server
spec:
  type: LoadBalancer
  ports:
    - name: nats-server
      port: 4222
      protocol: TCP
      targetPort: 4222
  loadBalancerIP: <x.x.x.x>
  selector:
    app: nats-server
EOF
```

Do I need to do something different for `v0.8.0` ?

Thanks.

**Comment by samstride** [comment]
Ok, so if anyone runs into the same issue with L4 loadbalancer , some changes where introduced in chart `v0.8.0` and above which requires the chart to be installed with a set of values and the load balancer needs to have the correct selector.

Install helm chart for nats as follows:

```sh
helm install nats-server nats/nats --namespace=nats \
    --set exporter.enabled=false \
    --set cluster.enabled=true \
    --set cluster.noAdvertise=true \    # This needs to be set
    --set cluster.replicas=3 \
    -f nats-affinity.yaml
```

Then setup L4 loadbalancer as follows:

```yaml
cat <<EOF | kubectl apply -n nats -f -
apiVersion: v1
kind: Service
metadata:
  name: nats-lb
  namespace: nats
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats   # correct selector needs to be set
  ports:
    - name: nats-server
      port: 4222
      protocol: TCP
      targetPort: 4222
  loadBalancerIP: <x.x.x.x>
EOF
```
