### ISSUE TITLE
setup.sh not working with newer version of k8

### ISSUE THREAD

**Issue by fabmade** [nats-io/k8s#247]
curl -sSL https://nats-io.github.io/k8s/setup.sh | sh

Error: unknown flag: --generator

see https://kubernetes.io/docs/reference/kubectl/conventions/

**Comment by huan** [comment]
I run into this issue today and it seems related to https://github.com/kubernetes/kubernetes/pull/68132

**Comment by eonward37** [comment]
Try using kubectl apply to create the setup container

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: nats-setup
spec:
  restartPolicy: Never
  serviceAccountName: nats-setup
  containers:
    - name: nats-setup
      image: synadia/nats-setup:latest
      imagePullPolicy: Always
EOF
```
