### ISSUE TITLE
Max payload K8s nats server

### ISSUE THREAD

**Issue by hieuhuynhdev** [nats-io/k8s#278]
Hi everyone,
At the moment I wanna add `max_payload: 4Mb` to a config file. But it not work. Please help me.
Thanks

My script:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats-config.conf: |
    max_payload: 4Mb
---
### NATS server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats:2.3.2-linux
          ports:
            - containerPort: 4222
              name: port4
            - containerPort: 6222
              name: port6
            - containerPort: 8222
              name: port8
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nats/
          command:
            - "nats-server"
            - "--config"
            - "/etc/nats/nats-config.conf"
      volumes:
        - name: config-volume
          configMap:
            name: nats-config
---
# NATS Service
apiVersion: v1
kind: Service
metadata:
  # this name must match the name in NATS_URL nats://<name_here>:4222
  name: nats
spec:
  type: NodePort
  selector:
    app: nats
  ports:
    - protocol: TCP
      name: port4
      port: 4222
      targetPort: 4222
    - protocol: TCP
      name: port6
      port: 6222
      targetPort: 6222
    - protocol: TCP
      name: port8
      port: 8222
      targetPort: 8222
---
```
