### ISSUE TITLE
Add support for NATS Jetstream Encryption Key

### ISSUE THREAD

**Issue by samuel-form3** [nats-io/k8s#294]
# Problem Statement
NATS chart there is no way to configure the Jetstream Encryption Key.

# Proposed Solution

Add an encryption section in jetstream configuration like the following:

```yaml
  jetstream:
    enabled: false

    ##########################
    #                        #
    #  Jetstream Encryption  #
    #                        #
    ##########################
    encryption:
      # Use key if you want to provide the key via Helm Values
      # key: "random_key"

      # Use a secret reference if you want to get a key from a secret
      # secret:
      #   name: "nats-jetstream-encryption"
      #   key: "key"
```
