### ISSUE TITLE
[nats helm] Manage pod labels with commonLabels

### ISSUE THREAD

**Issue by wigeric** [nats-io/k8s#298]
Chart version : 0.8.4

For now, the only labels added to pod via helm are selector labels.

We sometimes need to label the pods too.

changing the statefulset.yaml from
```yaml
spec:
  template:
    metadata:
      labels:
        {{- include "nats.selectorLabels" . | nindent 8 }}
```
to 
```yaml
spec:
  template:
    metadata:
      labels:
        {{- include "nats.labels" . | nindent 8 }}
```

would do the job as keeping the selectorLabels value and adding commonLabels
