### ISSUE TITLE
[helm] Upgrade from 2.3.4 to 2.4.0 is not stable

### ISSUE THREAD

**Issue by anjmao** [nats-io/k8s#312]
Just tried to upgrade from 2.3.4 to 2.4.0 version via helm chart.

```yaml
  nats:
    image: nats:2.4.0-alpine
    resources:
      requests:
        cpu: 1
        memory: 2Gi
      limits:
        cpu: 2
        memory: 2Gi

    limits:
      maxConnections:
      maxSubscriptions:
      maxControlLine:
      maxPayload:
      writeDeadline:
      maxPending:
      maxPings:
      lameDuckDuration:

    terminationGracePeriodSeconds: 60

    logging:
      debug:
      trace:
      logtime:
      connectErrorReports:
      reconnectErrorReports:

    jetstream:
      enabled: true

      memStorage:
        enabled: true

      fileStorage:
        enabled: true
        storageDirectory: /data
        storageClassName: standard
        size: 30Gi
        accessModes:
          - ReadWriteOnce

  cluster:
    enabled: true
    replicas: 3
    noAdvertise: false

  auth:
    enabled: true
    systemAccount:
    resolver:
      type: memory
      configMap:
        name: nats-accounts
        key: resolver.conf

  natsbox:
    enabled: false

  exporter:
    enabled: true   
```

Upgrade completely failed and streams stopped responding. Issues:

```
[ERR] RAFT [vURD0sM3 - S-R3F-pU5w3rId] Error sending snapshot to follower [yLCaJyhQ]: raft: no snapshot available
```

```
nats: no response from stream
```

No leader on stream. Also saw duplicate streams.
```
nats-js-0!, nats-js-1!, nats-js-2!
``` 

Also I tried to purge some problematic streams or change leader eg: `nats stream cluster step-down agent` but only received errors or timeouts.
