### ISSUE TITLE
It is not possible to template `.tpl.secret.name` values

### ISSUE THREAD

**Issue by kuznero** [nats-io/k8s#325]
I would like to make it possible to configure NATS like this from an umbrella helm chart:

```yaml
    tls:
      secret:
        name: "{{ .Release.Name }}-{{ .Values.nameOverride }}-cert-tls"
```

But currently it is not possible (`v0.8.9`).
