### ISSUE TITLE
Add heuristics for storage defaults

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#327]
The following will fail on EKS since there is no `default` volume name: 

```yaml
nats:
  image: synadia/nats-server:nightly

  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "2Gi"

    fileStorage:
      enabled: true
      size: "8Gi"
      storageDirectory: /data/
      storageClassName: default

cluster:
  enabled: true
  # Can set a custom cluster name
  # name: "nats"
  replicas: 3
```

```
storageclass.storage.k8s.io "default" not found
```
