### ISSUE TITLE
[Bug] When installing STAN in a cluster that uses Istio, the service port name "client" breaks the TCP connection

### ISSUE THREAD

**Issue by kevin-lindsay-1** [nats-io/k8s#359]
https://github.com/nats-io/k8s/blob/main/helm/charts/stan/templates/service.yaml#L19

If you change this:
```yaml
  ports:
  ...
  - name: client
    port: 4222
```

To this:
```yaml
  ports:
  ...
  - name: tcp-client
    port: 4222
```

The issue goes away instantly.
