### ISSUE TITLE
Allow for users to extend the generated config

### ISSUE THREAD

**Issue by TheQueenIsDead** [nats-io/k8s#385]
Hi there,

I was looking for the best way to configure nkey users in a new deployment means I am working on that involves this helm chart.

I am looking at storing nkeys in Hashicorp Vault, and deploying these as Kubernetes secrets via Terraform, outside of the Helm deployment process.

In order to not step on the toes of your convenient `nats.conf` generation in `templates/configmap.yml`, would a change be accepted that allows for users to define arbitrary `include` directives such that we can mount our own extra config in?
https://docs.nats.io/running-a-nats-service/configuration#include-directive

I see that we can include `customConfigSecret` but this seems to be mutually exclusive with the default generated config, and users may still want to benefit from the default build up, while opting to include other config items alongside this:

```
      # Common volumes for the containers.
      volumes:
      - name: config-volume
        {{ if .Values.nats.customConfigSecret }}
        secret:
          secretName: {{ .Values.nats.customConfigSecret.name }}
        {{ else }}
        configMap:
          name: {{ include "nats.fullname" . }}-config
        {{ end }}
```

The change would allow for us to provide our own authorization block (for example) from a secret / configmap, and allow us to separate out secrets from the Helm deployment process, something similar to the following (forgive the shoddy psedocode, the implementation would come out in the woodwork):
```
# configmap.yml
{{- if .Values.nats.config }}
{{- range .Values.nats.config }}
include ./{{ . }}.conf
{{- end }}
{{- end }}

# statefulset

container:
  volumeMounts:
    {{-for x }
volumes:
  {{- for x 

# values.yml
nats:
  config:
    auth:
      configMap:
        name: "nats-auth-configmap"
```

Happy to do the work, just trying to gauge interest from maintainers, thanks
