### ISSUE TITLE
Getting error when setting up NATS Account resolver --> nats-server: operators do not allow Accounts to be configured directly

### ISSUE THREAD

**Issue by WalterKhumalo** [nats-io/k8s#391]
Hi I am trying to set the NATS account resolver according to these instructions: https://artifacthub.io/packages/helm/nats/nats

Here is my nats config:

```
nats:
jetstream:
enabled: true

cluster:
  enabled: true
  name: "nats"
  replicas: 3

auth:
enabled: true
systemAccount: 
resolver:
  type: full
  operator: 
  systemAccount: 
  resolverPreload:
```
I have left out the user keys and the jwt information 

stan config:

```
stan:
  nats:
    serviceRoleAuth:
      enabled: false
  replicas: 3
store:
  cluster:
    enabled: true
  
cluster:
  name: "nats"
  
readinessProbe:
  httpGet:
    path: /streaming/serverz
    port: monitor
  timeoutSeconds: 2

livenessProbe:
  enabled: false
  probe:
    httpGet:
      path: /
      port: monitor
    timeoutSeconds: 2
```
When I start up the NATS server  I get the following error: nats-server: operators do not allow Accounts to be configured directly
