### ISSUE TITLE
nats-kafka chart encodes ">" in subject

### ISSUE THREAD

**Issue by OpenGuidou** [nats-io/k8s#406]
Hello,

Using the nats-kafka chart, if we provide the subject using a ">", it's converted to "\u003e" in the corresponding JSON config.
Then the application is unable to start.

Example:
```
- type: "NATSToKafka"
      brokers:
        - localhost:9092
      id: someid
      topic: sometopic
      subject: somesubject.>
```

result:
```
{
        "brokers": [
          "localhost:9092"
        ],
        "id": "someid",
        "subject": "somesubject.\u003e",
        "topic": "sometopic",
        "type": "NATSToKafka"
}
```
