### ISSUE TITLE
Stan ignores limit and volume config values

### ISSUE THREAD

**Issue by willfore** [nats-io/k8s#431]
I have the following values.yml file I'm feeding to helm when installing stan. It seems as though the limits and storageSize parameters are being ignored. Can you please point out what I may have configured wrong?

```
stan:
  image: nats-streaming:0.22
  replicas: 3
  clusterID: cluster1
  store:
    type: file
    limits:
      max_age: "72h"
      channels:
        max_age: "72h"
    cluster:
      enabled: true
    volume:
      enabled: true
      mount: /data/stan
      storageSize: "5Gi"
      accessModes: ReadWriteOnce
      storageClass: "longhorn"
```

It starts just fine but it's using the defaults of no max age and 1Gi for storageSize.

**Comment by willfore** [comment]
correct layout:

```
stan:
  image: nats-streaming:0.22
  replicas: 3
  clusterID: cluster1
store:
  type: file
  limits:
    max_age: 72h
  cluster:
    enabled: true
  volume:
    enabled: true
    mount: /data/stan
    storageSize: "5Gi"
    accessModes: ReadWriteOnce
    storageClass: "longhorn"
 ```
