### ISSUE TITLE
I modified the following configuration. After successful installation, nats-box prompts JetStream not enabled for account (10039)

### ISSUE THREAD

**Issue by MacGyverXie** [nats-io/k8s#444]
```yaml
nats:
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "1Gi"

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/
      storageClassName:

cluster:
  enabled: true
  replicas: 3
  noAdvertise: false

auth:
  enabled: true

  operatorjwt:
    configMap:
      name: operator-jwt
      key: KO.jwt

  systemAccount:

  resolver:
    type: memory

    configMap:
      name: nats-accounts
      key: resolver.conf
```
