### ISSUE TITLE
0.14.0 breaks generated YAML

### ISSUE THREAD

**Issue by burner-account** [nats-io/k8s#466]
Relocating the data part of [helm/charts/nats/templates/configmap.yaml](https://github.com/nats-io/k8s/commit/3e259f1980fe5db9b369f3465e0e1e51ad316047#diff-a135d042cfafb1f4f5f7ce8b1bbb4aefba0e2b793035c3b09a55b74cc8663175) to [helm/charts/nats/files/configmap/nats.conf](https://github.com/nats-io/k8s/commit/3e259f1980fe5db9b369f3465e0e1e51ad316047#diff-b6b6aa34a014b3ddd8915cd5c332e0bfdef655505c762957753625266dff643d) seems to have introduced an  error (formatting/line-break).

If you `helm template` nats/nats, you get
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-core-config
  namespace: nats-ns
  labels:
    helm.sh/chart: nats-0.14.0
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-core
    app.kubernetes.io/version: "2.7.3"
    app.kubernetes.io/managed-by: Helm
data:
  nats.conf: |
    <... snip ...>
    #####################
    #                   #
    # TLS Configuration #
    #                   #
    #####################tls {
      cert_file: /etc/nats-certs/clients/nats-server-tls/tls.crt
      key_file:  /etc/nats-certs/clients/nats-server-tls/tls.key
      ca_file: /etc/nats-certs/clients/nats-server-tls/ca.crt
  }

```
This seems to have some trouble with the "tls" subtree.

I think this is the reason why i get `Error: INSTALLATION FAILED: YAML parse error on nats/templates/configmap.yaml: error converting YAML to JSON: yaml: line 34: did not find expected key"` returned by helm install.
