### ISSUE TITLE
Failed to start: mkdir /data/stan/log: permission denied

### ISSUE THREAD

**Issue by etix** [nats-io/k8s#48]
Using a very simple helm deployment, Stan failed to start with message:
`Failed to start: mkdir /data/stan/log: permission denied`

It might be related to the drop of permissions from the security context.

```
store:
  type: file
  file:
    storageSize: 10Gi
  cluster:
    enabled: true
```
