### ISSUE TITLE
cannot patch "nats" with kind StatefulSet: StatefulSet.apps "nats" is invalid

### ISSUE THREAD

**Issue by artooro** [nats-io/k8s#485]
Attempting to upgrade from nats v2.6.3 (chart 0.9.2) to v2.7.4 (chart 0.15.1)

Currently live statefulset details:
```
kubectl -n nats get statefulset nats -o yaml 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    meta.helm.sh/release-name: nats
    meta.helm.sh/release-namespace: nats
  creationTimestamp: "2021-10-28T21:17:48Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: nats
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nats
    app.kubernetes.io/version: 2.6.3
    helm.sh/chart: nats-0.9.2
```

Steps taken to upgrade
```
helm repo update
helm -n nats get values nats > values.yaml
helm -n nats upgrade nats -f values.yaml nats/nats
```

Error output
```
Error: UPGRADE FAILED: cannot patch "nats" with kind StatefulSet: StatefulSet.apps "nats" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden
```

After attempting the upgrade it's in a failure status.
```
helm -n nats list
NAME	NAMESPACE	REVISION	UPDATED                            	STATUS	CHART      	APP VERSION
nats	nats     	5       	2022-04-07 22:23:11.81018 -0400 EDT	failed	nats-0.15.1	2.7.4      
```

I realize I could probably just delete the statefulset manually and attempt the upgrade again, but before I do I want to report this and see if there's anything else I can provide to prevent this issue for others.
