### ISSUE TITLE
After helm chart update, healthcheck return 404 for all nodes (Startup probe failed: HTTP probe failed with statuscode: 404)

### ISSUE THREAD

**Issue by kamilgregorczyk** [nats-io/k8s#503]
Hello, after upgrading nats helm chart to the newest version:

```
➜  ~ helm list -n nats
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION
nats	nats     	1       	2022-05-13 10:00:30.374979984 +0000 UTC	deployed	nats-0.16.0	2.8.0
```

the healthcheck started to return 404 for some reason:
```
➜  ~ kubectl get pods -n nats
NAME     READY   STATUS    RESTARTS   AGE
nats-2   2/3     Running   24         127m
nats-0   2/3     Running   24         127m
nats-1   2/3     Running   24         127m
```

```
➜  ~ kubectl describe pod -n nats nats-0
Name:         nats-0
Namespace:    nats
Priority:     0
Node:         worker1/192.168.0.202
Start Time:   Fri, 13 May 2022 12:00:41 +0200
Labels:       app.kubernetes.io/instance=nats
              app.kubernetes.io/name=nats
              controller-revision-hash=nats-cfdd9b6dc
              statefulset.kubernetes.io/pod-name=nats-0
Annotations:  checksum/config: 4d2451b073c8a1ff513c95d79d27a55a510087413c04fed8f1782cc4b695cd9a
              prometheus.io/path: /metrics
              prometheus.io/port: 7777
              prometheus.io/scrape: true
Status:       Running
IP:           10.42.1.127
IPs:
  IP:           10.42.1.127
Controlled By:  StatefulSet/nats
Containers:
  nats:
    Container ID:  containerd://5f868586b53850550070eef7d39a99fd962227fe9cfa5c7851e20d31fdf80349
    Image:         nats:alpine
    Image ID:      docker.io/library/nats@sha256:b524afdb0c81474b872f461444cbb51ead8684b87a166442e405d514586ac559
    Ports:         4222/TCP, 6222/TCP, 8222/TCP, 7777/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      nats-server
      --config
      /etc/nats-config/nats.conf
    State:          Running
      Started:      Fri, 13 May 2022 14:04:52 +0200
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 13 May 2022 13:59:42 +0200
      Finished:     Fri, 13 May 2022 14:04:52 +0200
    Ready:          False
    Restart Count:  24
    Liveness:       http-get http://:8222/ delay=10s timeout=5s period=30s #success=1 #failure=3
    Startup:        http-get http://:8222/healthz delay=10s timeout=5s period=10s #success=1 #failure=30
    Environment:
      POD_NAME:           nats-0 (v1:metadata.name)
      SERVER_NAME:        $(POD_NAME)
      POD_NAMESPACE:      nats (v1:metadata.namespace)
      CLUSTER_ADVERTISE:  $(POD_NAME).nats.$(POD_NAMESPACE).svc.cluster.local
    Mounts:
      /data/jetstream from nats-js-pvc (rw)
      /etc/nats-config from config-volume (rw)
      /var/run/nats from pid (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bj7wf (ro)
  reloader:
    Container ID:  containerd://46de8123440554aad46686bbe7f477b42b7011282177cc1314588e21e17e436d
    Image:         natsio/nats-server-config-reloader:0.6.3
    Image ID:      docker.io/natsio/nats-server-config-reloader@sha256:b310e8766c507a20dae7c634b81b49b47682e2ec985c0cd8b3c746660febb9fe
    Port:          <none>
    Host Port:     <none>
    Command:
      nats-server-config-reloader
      -pid
      /var/run/nats/nats.pid
      -config
      /etc/nats-config/nats.conf
    State:          Running
      Started:      Fri, 13 May 2022 12:01:00 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/nats-config from config-volume (rw)
      /var/run/nats from pid (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bj7wf (ro)
  metrics:
    Container ID:  containerd://9c28ed3ed609b33fcdcf9feb8efc2906c2911e5bcfd9955091f2476488ad031d
    Image:         natsio/prometheus-nats-exporter:0.9.1
    Image ID:      docker.io/natsio/prometheus-nats-exporter@sha256:4665cdc7e749548ee9999764f29665aaeeecac95f310319016764ba2ab25e1c1
    Port:          7777/TCP
    Host Port:     0/TCP
    Args:
      -connz
      -routez
      -subz
      -varz
      -prefix=nats
      -use_internal_server_id
      -jsz=all
      http://localhost:8222/
    State:          Running
      Started:      Fri, 13 May 2022 12:01:01 +0200
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-bj7wf (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  nats-js-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  nats-js-pvc-nats-0
    ReadOnly:   false
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nats-config
    Optional:  false
  pid:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-bj7wf:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  **Warning  Unhealthy  2m5s (x725 over 126m)  kubelet  Startup probe failed: HTTP probe failed with statuscode: 404**
```

How to reproduce:
```
 helm upgrade --install -f nats.yaml nats nats/nats --namespace nats --create-namespace
```

nats.yaml
```
nats:
  image: nats:alpine
  jetstream:
    enabled: true

    memStorage:
      enabled: false
      size: 2Gi

    fileStorage:
      enabled: true
      storageDirectory: /data/jetstream
      size: 10Gi
      storageClassName: longhorn

auth:
  enabled: true
  basic:
    users:
      - user: exposee
        password: exposee
      - user: admin
        password: admin
    accounts:
      USERS:
        jetstream: enable
        users:
          - user: exposee
            password: exposee
      SYS:
        users:
          - user: admin
            password: admin
  systemAccount: SYS

cluster:
  enabled: true
  replicas: 3

exporter:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: prometheus

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - nats

natsbox:
  enabled: false
```

**Comment by kamilgregorczyk** [comment]
logs from one of the instances:
```
[693] 2022/05/13 12:10:03.824605 [INF] Starting nats-server
[693] 2022/05/13 12:10:03.824730 [INF]   Version:  2.6.4
[693] 2022/05/13 12:10:03.824738 [INF]   Git:      [a27de5a]
[693] 2022/05/13 12:10:03.824744 [INF]   Name:     nats-0
[693] 2022/05/13 12:10:03.824769 [INF]   Node:     S1Nunr6R
[693] 2022/05/13 12:10:03.824788 [INF]   ID:       NANZGVLPUYSDSUGVFHZZHJU52BXPNHPN5IY3FQ2X7OBPDKLCI6JAYBZ3
[693] 2022/05/13 12:10:03.824835 [WRN] Plaintext passwords detected, use nkeys or bcrypt
[693] 2022/05/13 12:10:03.824856 [INF] Using configuration file: /etc/nats-config/nats.conf
[693] 2022/05/13 12:10:03.827881 [INF] Starting JetStream
[693] 2022/05/13 12:10:03.828223 [INF]     _ ___ _____ ___ _____ ___ ___   _   __  __
[693] 2022/05/13 12:10:03.828242 [INF]  _ | | __|_   _/ __|_   _| _ \ __| /_\ |  \/  |
[693] 2022/05/13 12:10:03.828248 [INF] | || | _|  | | \__ \ | | |   / _| / _ \| |\/| |
[693] 2022/05/13 12:10:03.828253 [INF]  \__/|___| |_| |___/ |_| |_|_\___/_/ \_\_|  |_|
[693] 2022/05/13 12:10:03.828258 [INF] 
[693] 2022/05/13 12:10:03.828264 [INF]          https://docs.nats.io/jetstream
[693] 2022/05/13 12:10:03.828269 [INF] 
[693] 2022/05/13 12:10:03.828274 [INF] ---------------- JETSTREAM ----------------
[693] 2022/05/13 12:10:03.828288 [INF]   Max Memory:      11.63 GB
[693] 2022/05/13 12:10:03.828296 [INF]   Max Storage:     10.00 GB
[693] 2022/05/13 12:10:03.828302 [INF]   Store Directory: "/data/jetstream/jetstream"
[693] 2022/05/13 12:10:03.828307 [INF] -------------------------------------------
[693] 2022/05/13 12:10:03.828992 [INF] Starting JetStream cluster
[693] 2022/05/13 12:10:03.829011 [INF] Creating JetStream metadata controller
[693] 2022/05/13 12:10:03.829752 [INF] JetStream cluster recovering state
[693] 2022/05/13 12:10:03.834489 [INF] Starting http monitor on 0.0.0.0:8222
[693] 2022/05/13 12:10:03.834663 [INF] Listening for client connections on 0.0.0.0:4222
[693] 2022/05/13 12:10:03.835191 [INF] Server is ready
[693] 2022/05/13 12:10:03.835252 [INF] Cluster name is nats
[693] 2022/05/13 12:10:03.835322 [INF] Listening for route connections on 0.0.0.0:6222
[693] 2022/05/13 12:10:03.842270 [INF] 10.42.2.30:6222 - rid:7 - Route connection created
[693] 2022/05/13 12:10:03.842314 [INF] 10.42.0.35:6222 - rid:8 - Route connection created
[693] 2022/05/13 12:10:04.482076 [INF] 10.42.0.35:41694 - rid:9 - Route connection created
```

**Comment by kamilgregorczyk** [comment]
```
startupProbe:
        httpGet:
          path: /healthz
          port: 8222
          scheme: HTTP
```

looks like this method is no longer available whereas the liveness check uses:

```
livenessProbe:
        httpGet:
          path: /
          port: 8222
          scheme: HTTP

``` and this one works

should startupProbe also use `/` ?
