### ISSUE TITLE
Add tlsConfig configuration to Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by in-cloud-opensource** [nats-io/k8s#509]
To be able to configure the Prometheus service monitor with custom TLS config, support tlsConfig in helm chart.

Extension for the exporter configuration:
``` yaml
exporter:
  enabled: true
  #...
  serviceMonitor:
    enabled: true
    # ...
    # new configuration for tls configuration    
    tlsConfig:
      caFile: /etc/istio-certs/root-cert.pem
      certFile: /etc/istio-certs/cert-chain.pem
      insecureSkipVerify: true
      keyFile: /etc/istio-certs/key.pem
```

Needs to be evaluated in the `servcieMonitor.yaml`
``` yaml
  tlsConfig:
    {{- toYaml .Values.exporter.serviceMonitor.tlsConfig | nindent  6 }}
```
