### ISSUE TITLE
Declare multi type authorizations

### ISSUE THREAD

**Issue by hhk7734** [nats-io/k8s#547]
I want to use both user & password and nkey.
But the first one dose not work, the second one works. is this intended?

```yaml
auth:
  enabled: true

  basic:
    users:
      - user: <user>
        password: <password>

  nkeys:
    users:
      - nkey: <nkey-user>
```

```yaml
auth:
  enabled: true

  basic:
    users:
      - user: <user>
        password: <password>
      - nkey: <nkey-user>
```
