### ISSUE TITLE
Can't using with an existing PersistentVolumeClaim

### ISSUE THREAD

**Issue by Doslin** [nats-io/k8s#559]
```yaml
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    #memStorage:
    # enabled: true
    # size: "2Gi"

    fileStorage:
      enabled: true
      size: "2Gi"
      #storageDirectory: /data/
      #existingClaim: nats-js-disk
      # storageClassName: gp2 # NOTE: AWS setup but customize as needed for your infra.

cluster:
  enabled: false
  # Can set a custom cluster name
  # name: "nats"
  noAdvertise: true
  replicas: 1

auth:
  enabled: false
```
As soon as I set existingClaim, I get an error when I start nats-server by ` helm install zhilin-nats nats/nats -f nats.yaml`
<img width="741" alt="image" src="https://user-images.githubusercontent.com/29807388/187826722-5e577bd6-d936-4422-a937-4459fef668cb.png">

**Comment by Doslin** [comment]
❯ cat nats-pvc.yaml
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nats-js-disk
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```
kubectl get pvc
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
nats-js-disk                       Bound    pvc-d7cb93ee-fecc-4c81-be3c-a8024524633d   10Gi       RWO            standard       31m

<img width="937" alt="image" src="https://user-images.githubusercontent.com/29807388/187827345-5669fc4a-a9e7-4046-9a9d-85a0a51317d6.png">
