### ISSUE TITLE
how to config surveyor jetstream  by use  secret to js-user.creds

### ISSUE THREAD

**Issue by Doslin** [nats-io/k8s#565]
![image](https://user-images.githubusercontent.com/29807388/188620592-86648018-7638-4974-a670-67546045df3a.png)
```yaml
...
  credentials:
    secret:
      name: nats-sys-creds
      key: js-user.creds

  # Required for NATS mutual TLS
  # tls:
  #    secret:
  #      name: nats-client-tls
  #    ca: "ca.crt" # optional
  #    cert: "tls.crt"
  #    key: "tls.key"

  jetstream:
    enabled: true
    # accounts:
    # - name: test
    #   tls:
    #     secret:
    #       name: test-user-tls
    #     ca: "ca.crt" # optional
    #     cert: "tls.crt"
    #     key: "tls.key"
```

**Comment by mxchinegod** [comment]
Seconding this for leaf nodes. How do we use .creds files to authenticate to ngs? Cannot find any method of assigning volumes via secrets.

**Comment by avacaru** [comment]
```yaml
conifg:
  leafnodes:
      enabled: true
      merge:
        remotes:
          - url:  nats-leaf://nats.my-cluster.net:7422
            credentials: /etc/nats-creds/secret.creds
podTemplate:
  patch:
    - op: add
      path: /spec/volumes/-
      value:
        name: nats-creds
        secret:
          secretName: nats-creds
container:
  patch:
    - op: add
      path: /volumeMounts/-
      value:
        name: nats-creds
        mountPath: /etc/nats-creds
extraResources:
- apiVersion: v1
  kind: Secret
  metadata:
    name: nats-creds
  data:
    secret.creds:
      $tplYaml: >
        {{ .Values.secret.creds | b64enc}}
```
