### ISSUE TITLE
nats.pid: no such file or directory

### ISSUE THREAD

**Issue by thiDucTran** [nats-io/k8s#570]
Hi, I am seeing the errors below. I read https://github.com/nats-io/k8s/issues/219 and https://github.com/nats-io/k8s/issues/185 but seems my issue is not the same.

```
Stream closed EOF for nats-testing/nats-thi-0 (nats)
reloader 2022/09/15 20:47:02 Starting NATS Server Reloader v0.7.2
reloader 2022/09/15 20:47:02 Error: open /var/run/nats/nats.pid: no such file or directory
reloader 2022/09/15 20:47:04 Error: open /var/run/nats/nats.pid: no such file or directory                                                                                                                       reloader 2022/09/15 20:47:06 Error: open /var/run/nats/nats.pid: no such file or directory                                                                                                                       reloader 2022/09/15 20:47:08 Error: open /var/run/nats/nats.pid: no such file or directory                                                                                                                       reloader 2022/09/15 20:47:10 Error: open /var/run/nats/nats.pid: no such file or directory                                                                                                                       reloader 2022/09/15 20:47:12 Error: open /var/run/nats/nats.pid: no such file or directory                                                                                                                       reloader Error: Too many errors attempting to find server process 
```

I am doing helm install like below

```yaml
helm install nats-thi nats/nats --namespace nats-testing --set nats.logging.connectErrorReports="true" --set nats.logging.logtime="true" --set nats.logging.reconnectErrorReports="true" --set cluster.enabled="true" --set cluster.replicas=3 --set nats.jetstream.fileStorage.existingClaim="nats-azurefile-claim" --set nats.jetstream.fileStorage.claimStorageSize="10Gi" --dry-run
NAME: nats-thi
LAST DEPLOYED: Thu Sep 15 20:45:36 2022
NAMESPACE: nats-testing
STATUS: pending-install
REVISION: 1
HOOKS:
---
# Source: nats/templates/tests/test-request-reply.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "nats-thi-test-request-reply"
  labels:
    chart: nats-0.17.5
    app: nats-thi-test-request-reply
  annotations:
    "helm.sh/hook": test
spec:
  containers:
  - name: nats-box
    image: synadia/nats-box
    env:
    - name: NATS_HOST
      value: nats-thi
    command:
    - /bin/sh
    - -ec
    - |
      nats reply -s nats://$NATS_HOST:4222 'name.>' --command "echo 1" &
    - |
      "&&"
    - |
      name=$(nats request -s nats://$NATS_HOST:4222 name.test '' 2>/dev/null)
    - |
      "&&"
    - |
      [ $name = test ]

  restartPolicy: Never
MANIFEST:
---
# Source: nats/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nats-thi
  namespace: nats-testing
  labels:
    helm.sh/chart: nats-0.17.5
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: nats-thi
---
# Source: nats/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-thi
  namespace: nats-testing
  labels:
    helm.sh/chart: nats-0.17.5
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
---
# Source: nats/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-thi-config
  namespace: nats-testing
  labels:
    helm.sh/chart: nats-0.17.5
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
data:
  nats.conf: |
    # NATS Clients Port
    port: 4222

    # PID file shared with configuration reloader.
    pid_file: "/var/run/nats/nats.pid"

    ###############
    #             #
    # Monitoring  #
    #             #
    ###############
    http: 8222
    server_name:$POD_NAME
    ###################################
    #                                 #
    # NATS Full Mesh Clustering Setup #
    #                                 #
    ###################################
    cluster {
      port: 6222

      routes = [
        nats://nats-thi-0.nats-thi.nats-testing.svc.cluster.local:6222,nats://nats-thi-1.nats-thi.nats-testing.svc.cluster.local:6222,nats://nats-thi-2.nats-thi.nats-testing.svc.cluster.local:6222,

      ]
      cluster_advertise: $CLUSTER_ADVERTISE

      connect_retries: 120
    }
    logtime: true
    connect_error_reports: true
    reconnect_error_reports: true
    lame_duck_grace_period: 10s
    lame_duck_duration: 30s
---
# Source: nats/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nats-thi
  namespace: nats-testing
  labels:
    helm.sh/chart: nats-0.17.5
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: client
    port: 4222
    appProtocol: tcp
  - name: cluster
    port: 6222
    appProtocol: tcp
  - name: monitor
    port: 8222
    appProtocol: http
  - name: metrics
    port: 7777
    appProtocol: http
  - name: leafnodes
    port: 7422
    appProtocol: tcp
  - name: gateways
    port: 7522
    appProtocol: tcp
---
# Source: nats/templates/nats-box.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-thi-box
  namespace: nats-testing
  labels:
    app: nats-thi-box
    chart: nats-0.17.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-thi-box
  template:
    metadata:
      labels:
        app: nats-thi-box
    spec:
      volumes:
      containers:
      - name: nats-box
        image: natsio/nats-box:0.11.0
        imagePullPolicy: IfNotPresent
        resources:
          null
        env:
        - name: NATS_URL
          value: nats-thi
        command:
        - "tail"
        - "-f"
        - "/dev/null"
        volumeMounts:
---
# Source: nats/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-thi
  namespace: nats-testing
  labels:
    helm.sh/chart: nats-0.17.5
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: nats-thi
    app.kubernetes.io/version: "2.8.4"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: nats-thi
  replicas: 3
  serviceName: nats-thi

  podManagementPolicy: Parallel

  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "7777"
        prometheus.io/scrape: "true"
        checksum/config: 72ce116d645c06371ef0b448be2b2fc8765e48ffe88f320b252aaeaa9ee67fba
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: nats-thi
    spec:
      # Common volumes for the containers.
      volumes:
      - name: config-volume
        configMap:
          name: nats-thi-config

      # Local volume shared with the reloader.
      - name: pid
        emptyDir: {}

      #################
      #               #
      #  TLS Volumes  #
      #               #
      #################

      serviceAccountName: nats-thi

      # Required to be able to HUP signal and apply config
      # reload to the server without restarting the pod.
      shareProcessNamespace: true

      #################
      #               #
      #  NATS Server  #
      #               #
      #################
      terminationGracePeriodSeconds: 60
      containers:
      - name: nats
        image: nats:2.8.4-alpine
        imagePullPolicy: IfNotPresent
        resources:
          {}
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        - containerPort: 7777
          name: metrics

        command:
        - "nats-server"
        - "--config"
        - "/etc/nats-config/nats.conf"

        # Required to be able to define an environment variable
        # that refers to other environment variables.  This env var
        # is later used as part of the configuration file.
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVER_NAME
          value: $(POD_NAME)
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_ADVERTISE
          value: $(POD_NAME).nats-thi.$(POD_NAMESPACE).svc.cluster.local
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats


        #######################
        #                     #
        # Healthcheck Probes  #
        #                     #
        #######################
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            # for NATS server versions >=2.7.1, healthz will be enabled to allow for a grace period
            # in case of JetStream enabled deployments to form quorum and streams to catch up.
            path: /healthz
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30

        # Gracefully stop NATS Server on pod deletion or image upgrade.
        #
        lifecycle:
          preStop:
            exec:
              # send the lame duck shutdown signal to trigger a graceful shutdown
              # nats-server will ignore the TERM signal it receives after this
              #
              command:
              - "nats-server"
              - "-sl=ldm=/var/run/nats/nats.pid"

      #################################
      #                               #
      #  NATS Configuration Reloader  #
      #                               #
      #################################
      - name: reloader
        image: natsio/nats-server-config-reloader:0.7.2
        imagePullPolicy: IfNotPresent
        resources:
          null
        command:
        - "nats-server-config-reloader"
        - "-pid"
        - "/var/run/nats/nats.pid"
        - "-config"
        - "/etc/nats-config/nats.conf"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats-config
        - name: pid
          mountPath: /var/run/nats


      ##############################
      #                            #
      #  NATS Prometheus Exporter  #
      #                            #
      ##############################
      - name: metrics
        image: natsio/prometheus-nats-exporter:0.10.0
        imagePullPolicy: IfNotPresent
        resources:
          {}
        args:
        - -connz
        - -routez
        - -subz
        - -varz
        - -prefix=nats
        - -use_internal_server_id
        - http://localhost:8222/
        ports:
        - containerPort: 7777
          name: metrics

  volumeClaimTemplates:

NOTES:
You can find more information about running NATS on Kubernetes
in the NATS documentation website:

  https://docs.nats.io/nats-on-kubernetes/nats-kubernetes

NATS Box has been deployed into your cluster, you can
now use the NATS tools within the container as follows:

  kubectl exec -n nats-testing -it deployment/nats-thi-box -- /bin/sh -l

  nats-box:~# nats-sub test &
  nats-box:~# nats-pub test hi
  nats-box:~# nc nats-thi 4222

Thanks for using NATS!
```
