### ISSUE TITLE
Helm: store.file.path does not seem to be working on NFS

### ISSUE THREAD

**Issue by samstride** [nats-io/k8s#58]
Hi,

I have attached an NFS to our k8s cluster at path `/var/mnt`

I have installed nats + stan using the latest helm charts (as of this writing) like this

```sh
helm install nats-server nats/nats --namespace=nats 

helm install stan-server nats/stan --namespace=nats \
  --set stan.nats.url=nats://nats-server:4222 \
  --set store.type=file \
  --set store.file.path=/var/mnt/nats \
  --set store.file.storageSize=1Gi
```

The startup log from stan shows the NFS path being set

```
[1] 2020/05/13 04:03:38.932852 [INF] STREAM: Starting nats-streaming-server[stan-server] version 0.17.0
[1] 2020/05/13 04:03:38.933013 [INF] STREAM: ServerID: xDec25eoUVPr0wxKKaj7xS
[1] 2020/05/13 04:03:38.933029 [INF] STREAM: Go version: go1.13.7
[1] 2020/05/13 04:03:38.933041 [INF] STREAM: Git commit: [f4b7190]
[1] 2020/05/13 04:03:38.943212 [INF] STREAM: Recovering the state...
[1] 2020/05/13 04:03:38.945227 [INF] STREAM: No recovered state
[1] 2020/05/13 04:03:39.196686 [INF] STREAM: Message store is FILE
[1] 2020/05/13 04:03:39.196697 [INF] STREAM: Store location: /var/mnt/nats
[1] 2020/05/13 04:03:39.196721 [INF] STREAM: ---------- Store Limits ----------
[1] 2020/05/13 04:03:39.196723 [INF] STREAM: Channels:                  100 *
[1] 2020/05/13 04:03:39.196725 [INF] STREAM: --------- Channels Limits --------
[1] 2020/05/13 04:03:39.196726 [INF] STREAM:   Subscriptions:          1000 *
[1] 2020/05/13 04:03:39.196727 [INF] STREAM:   Messages     :       1000000 *
[1] 2020/05/13 04:03:39.196728 [INF] STREAM:   Bytes        :     976.56 MB *
[1] 2020/05/13 04:03:39.196730 [INF] STREAM:   Age          :     unlimited *
[1] 2020/05/13 04:03:39.196731 [INF] STREAM:   Inactivity   :     unlimited *
[1] 2020/05/13 04:03:39.196732 [INF] STREAM: ----------------------------------
[1] 2020/05/13 04:03:39.196734 [INF] STREAM: Streaming Server is ready
```

However, when I look at my NFS, `clients.dat` and `server.dat` and the subjects are being created at `/var/mnt`

I even created the folder at `/var/mnt/nats` but that didn't seem to help either. I even tried setting `securityContext` to null but that didn't work either.

Is there something I am doing wrong?

Thanks.

**Comment by wallyqs** [comment]
Thanks for filing the report, this should be fixed now via #59 

Also here is an example of how it should work now with NFS with the new `volume` declaration block:

```yaml
stan:
  replicas: 2
  nats:
    url: "nats://my-nats:4222"

store:
  type: file

  # 
  # Fault tolerance group
  # 
  ft:
    group: foo

  # 
  # File storage settings.
  # 
  file:
    path: /data/stan/store

  # volume for EFS
  volume:
    mount: /data/stan
    storageSize: 1Gi
    storageClass: aws-efs
    accessModes: ReadWriteMany
```
