### ISSUE TITLE
JetStream cluster never gets healthy with podManagementPolicy=OrderedReady

### ISSUE THREAD

**Issue by marre** [nats-io/k8s#594]
Hi,

I am upgrading an older NATS cluster (with podManagementPolicy=OrderedReady) by adding support for JetStream, but when scaling up from 0 pods to 3 the cluster never gets healthy.

The health check endpoint responds with:
```
/ # curl http://127.0.0.1:8222/healthz
{"status":"unavailable","error":"JetStream has not established contact with a meta leader"}
```

Reproducible with the following values file (nats.yaml):
```
cluster:
  enabled: true
  replicas: 3

nats:
  jetstream:
    enabled: true

podManagementPolicy: OrderedReady
```

And then installing nats with:
```
helm install nats nats/nats --values nats.yaml
```

Seems like a clustered JetStream never get "healthy" if there is only one pod running. Is this intentional?

**Comment by caleblloyd** [comment]
`podManagementPolicy` really does need to be `Parallel` because in a 3-node cluster when all 3 nodes go down, 2 have to come up to establish quorom.  Unfortunately in k8s that field is immuitable, so this would mean re-creating the stateful set

One thing you could do as a workaround to get the cluster up is disable the health probes temporarily with:

```yaml
nats:
  healthcheck:
    liveness:
      enabled: false
    readiness:
      enabled: false
    startup:
      enabled: false
```

Then re-enable the health probes, and updates should still work gracefully from there
