### ISSUE TITLE
Jetstream problem with rolling restart in helm 0.19.3, works fine in 0.19.1

### ISSUE THREAD

**Issue by marre** [nats-io/k8s#614]
Using the following nats.yaml:
```
nats:
  healthcheck:
    enableHealthzLivenessReadiness: true

  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: "1Gi"

    fileStorage:
      enabled: false

cluster:
  enabled: true
  replicas: 3

auth:
  enabled: true

  systemAccount: sys

  basic:
    accounts:
      sys:
        users:
        - user: sys
          pass: sys
```

Create a separate namespace:
```
kubectl create namespace jetstream
```

And install 0.19.3 (nats 2.9.9):
```
helm install -n jetstream --version 0.19.3 nats nats/nats -f nats.yaml
```

Then watching the stream report from the nats-box in one window:
```
watch kubectl -n jetstream exec -it deployment/nats-box -- nats stream report
```

Create a stream (go with the rest as defaults):
```
kubectl -n jetstream exec -it deployment/nats-box -- nats stream add --storage=memory --replicas=3 --max-bytes=30Mib --retention=work --subjects="com.whatever.start" start
```

Waiting for the stream to pop up in the nats stream report window

Then trigger a rolling restart with:
```
kubectl -n jetstream rollout restart statefulset nats
```

And wait for the nodes to restart, one by one. And wait for them to be ready again.

Notice that the stream goes offline in the nats stream report window:
```
Obtaining Stream stats

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                              Stream Report                                              │
├────────┬─────────┬───────────┬───────────┬──────────┬───────┬──────┬─────────┬──────────────────────────┤
│ Stream │ Storage │ Placement │ Consumers │ Messages │ Bytes │ Lost │ Deleted │ Replicas                 │
├────────┼─────────┼───────────┼───────────┼──────────┼───────┼──────┼─────────┼──────────────────────────┤
│ start  │ Memory  │           │ 0         │ 0        │ 0 B   │ 0    │ 0       │ nats-0!, nats-1!, nats-2 │
╰────────┴─────────┴───────────┴───────────┴──────────┴───────┴──────┴─────────┴──────────────────────────╯
```
