### ISSUE TITLE
Adding a SYS user hides any existing streams

### ISSUE THREAD

**Issue by raypinto** [nats-io/k8s#617]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats-server` and affected client libraries used:
2.9.9

#### OS/Container environment:
Docker, K8s

#### Steps or code to reproduce the issue:

- Create the following config file:

conf.yaml
```
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3
```

- Install nats using latest helm charts using the command: 
  - `helm install nats nats/nats --values conf.yaml`

- Create a stream using the nats cli

- Create the following config file with basic auth:

config_new.yaml
```
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3

auth:
  enabled: true
  systemAccount: SYS
  basic:
    noAuthUser: user
    accounts:
      SYS:
        users:
        - user: sys
          password: sys
      \$G:
        users:
        - user: user
          password: user
        jetstream: true
```

- Upgrade nats using latest helm charts using the command: 
  - `helm upgrade nats nats/nats --values conf_new.yaml`

- Check the stream created before the upgrade. The stream does not show up when running: `nats stream ls`

#### Expected result:

The config reloader reloads the new auth config without restarting the nats servers. The stream is still present and can be used. 

#### Actual result:

The nats servers are restarted. The stream is not visible and  also any consumers that created earlier (if any) are not retrievable.

**Comment by derekcollison** [comment]
You should not need to define the no_auth user etc if you just want to add a system user to an existing account that has not credentials for the $G account.

Last config line is all that is needed.

**Comment by wallyqs** [comment]
@raypinto have PR up to help with your use case but as @derekcollison points, you may only need this:
```
nats:
  image: nats:alpine

  # Let only configuration reload handle updates (enabled by default)
  configChecksumAnnotation: false

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3

auth:
  enabled: true
  systemAccount: "$SYS"
  timeout: 5s
  basic:
    accounts:
      $SYS:
        users:
        - user: sys
          password: sys
```

Note that the system account is `"$SYS"` and not SYS.  Calling it `SYS` will cause the JS servers on restart report unknown account errors (since internally it was using `$SYS` which is the default), this will then cause startup probes to fail since it will never have quorum:

```
[8] 2022/12/19 19:26:35.584971 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$SYS.ACCOUNT.*.CLAIMS.UPDATE"
[8] 2022/12/19 19:26:35.585179 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$JSC.ARU.$G.*"
[8] 2022/12/19 19:26:35.585354 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$SYS.REQ.SERVER.PING.ROUTEZ"
[8] 2022/12/19 19:26:35.585487 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$SYS.REQ.ACCOUNT.*.SUBSZ"
[8] 2022/12/19 19:26:35.585640 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$SYS.ACCOUNT.*.LEAFNODE.CONNECT"
[8] 2022/12/19 19:26:35.585770 [ERR] 10.96.2.11:6222 - rid:9 - Unknown account "$SYS" for remote subject "$SYS.JSC.CONSUMER.ASSIGNMENT.RESULT"
```
