### ISSUE TITLE
warning logged on upgrade

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#619]
With something like:

```yaml
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3

auth:
  enabled: true
  systemAccount: "$SYS"
  timeout: 5s
  basic:
    accounts:
      $SYS:
        users:
        - user: sys
          password: sys
```

```
helm upgrade issue3722 ./helm/charts/nats  -f examples/b.yaml 
coalesce.go:220: warning: cannot overwrite table with non table for nats.nats.image (map[pullPolicy:IfNotPresent repository:nats tag:2.9.9-alpine])
```
