### ISSUE TITLE
Clustering enabled with podManagementPolicy OrderedReady is blocked by startup healthcheck

### ISSUE THREAD

**Issue by raypinto** [nats-io/k8s#622]
**Description:**

When installing nats with jetstream and clustering enabled and podManagementPolicy `OrderedReady`, the startup healthcheck blocks the creation of the statefulset with the error:

```
nats-0 nats [7] 2022/12/20 13:52:32.091167 [WRN] Healthcheck failed: "JetStream has not established contact with a meta leader"
```

This is obvious since there is no cluster formed and hence no quorum. But helm upgrade from podManagementPolicy `Parallel` to `OrderedReady` go through smoothly. Hence its not about putting an if clause in the nats chart.

**Steps to reproduce:**
- Using the following configuration install nats chart:

conf.yaml
```
nats:
  image: nats:alpine

  jetstream:
    enabled: true

    fileStorage:
      enabled: true
      size: "1Gi"
      storageDirectory: /data/

cluster:
  enabled: true
  replicas: 3

podManagementPolicy: OrderedReady
```

`helm install nats nats/nats --values ~/conf.yaml`
