### ISSUE TITLE
helm: add support for Prometheus service discovery

### ISSUE THREAD

**Issue by kamikaze139** [nats-io/k8s#63]
The default Prometheus service discovery configuration does not discover the endpoints at port 7777 exposed by prometheus-nats-exporter. One can add the endpoint manually to the Prometheus instance. Adding the Prometheus annotations enabling the scraping by default to the helm charts of stan and nats would remove this step.

E.g.
```yaml
"prometheus.io/scrape": "true"
"prometheus.io/path": "/metrics"
"prometheus.io/port": "7777"
```

Is it possible to add this feature?

**Comment by bw512** [comment]
It is possible to add them via the `podAnnotations` value, something like this is working for me: 

```yaml
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "7777"
  prometheus.io/scrape: "true"
``` 

I think it would make sense if these were there by default when exporter.enabled is set to true. I would be willing to contribute a PR for that if it would be of interest?
