### ISSUE TITLE
Nats: failed to start nats-box pod

### ISSUE THREAD

**Issue by joschiwald** [nats-io/k8s#665]
**Chart**: nats
**Version**: 0.19.9

When I try to install the nats helm chart on an restricted environment (e.g. openshift) which does not allow running containers as root, the nats-box pod will fail to start if a tls secret is specified.

Given following values during install:
```yaml
# values.yaml
nats:
  tls:
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
natsbox:
  enabled: true
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
```

This following command on pod start is unable to copy the tls certificate to `/usr/local/share/ca-certificates` due to permissing denied because that directory is owned by root.
```yaml
# templates/nats-box.yaml
lifecycle:
  postStart:
    exec:
      command:
        - /bin/sh
        - -c
        - cp /etc/nats-certs/clients/{{ $secretName }}/* /usr/local/share/ca-certificates && update-ca-certificates
```
Using a volume mount with `emptyDir` at `/usr/local/share/ca-certificates` would solve the issue with copying the tls secret but `update-ca-certificates` still requires root permissions on `/etc/ssl/certs/`.
