### ISSUE TITLE
websocket is not included in the network policy configuration

### ISSUE THREAD

**Issue by glehmann** [nats-io/k8s#690]
when activating both websocket and networkpolicy, the websocket port is not listed in the networkpolicy.

This prevent other pods, for examples the ones from the ingress, to reach the nats pods on that port, unless we define another network policy just for that outside of the nats helm chart, which is a bit strange given there is already one define in the chart.

```yaml
  websocket:
    enabled: true
  networkPolicy:
    enabled: true
```
