### ISSUE TITLE
max_file_store unset in nats.conf

### ISSUE THREAD

**Issue by r65535** [nats-io/k8s#716]
I've just deployed `1.0.0-beta.1` but it doesn't seem to set `max_file_store` in the nats.conf using the following values:
```
config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      enabled: true
        pvc:
          enabled: true
          size: 25Gi
```

I can set the value manually via `config.jetstream.fileStore.maxSize` but the comment in values.yaml states it should be set as the total available PVC size by default?
