### ISSUE TITLE
Feature: Use single PVC with subPaths

### ISSUE THREAD

**Issue by Zetanova** [nats-io/k8s#724]
It is currently not possible to use a single PVC per nats node over the helm chart.

To use the same volume for jetstream and jwt storage over the help of [k8s volume subPath](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) makes economical sense.

I lack the exp. in helm to add this feature myself.

**Comment by caleblloyd** [comment]
With the `1.x-beta` Helm Chart that is currently published you can do it with something like this:

```yaml
config:
  jetstream:
    enabled: true
    fileStore:
      maxSize: 10Gi
      pvc:
        enabled: false
  resolver:
    enabled:
      true
    pvc:
      enabled: false
statefulSet:
  patch:
  - op: add
    path: /spec/volumeClaimTemplates
    value: []
  - op: add
    path: /spec/volumeClaimTemplates/-
    value:
      metadata:
        name: js-and-resolver
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
container:
  patch:
  - op: add
    path: /volumeMounts/-
    value:
      name: js-and-resolver
      subPath: js
      mountPath:
        $tplYaml: >-
          {{ .Values.config.jetstream.fileStore.dir }}
  - op: add
    path: /volumeMounts/-
    value:
      name: js-and-resolver
      subPath: resolver
      mountPath:
        $tplYaml: >-
          {{ .Values.config.resolver.dir }}
```
