### ISSUE TITLE
natsbox secrets are mounted incorrectly

### ISSUE THREAD

**Issue by jleni** [nats-io/k8s#733]
Something like this 

```
natsBox:
  enabled: true
  # ############################################################
  # # NATS contexts
  # ############################################################
  contexts:
    default:
      creds:
        secretName: nats-box-creds
        key: default.creds
```

is generating

```
  default.json: |
    {
      "creds": "/etc/nats-creds/default/default.creds",
      "url": "nats://release-name-nats"
    }
```

but mounting at `/etc/nats-contents/default.creds` so credentials are later not foun.
