### ISSUE TITLE
Feature Request: nats-server: additionalInitContainers

### ISSUE THREAD

**Issue by siredmar** [nats-io/k8s#738]
I need to have a custom initContainer for nats-server where i need to gather some credentials from Hashicorp Vault and generate a config file. 

I propose a `additionalInitContainers` field in the values.yaml that adds these initContainers to the Statefulset.

**Comment by caleblloyd** [comment]
This is supported in the 1.x beta chart already.

**Comment by siredmar** [comment]
@caleblloyd would you tell me how to find this 1.x beta chart?

**Comment by siredmar** [comment]
For anyone who encounters something like my issue: 
Here is an example what i did in my values.yaml

```yaml
statefulSet:
  merge:
    metadata:
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.vault.svc:8200"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
    spec:
      initContainers:
        - name: prepare
          image: alpine
          command:
            [
              "sh",
              "-c",
              "echo $OPERATOR_JWT > /secrets/operator_jwt && echo $SYS_ACCOUNT_JWT > /secrets/sys_account_jwt && echo $SYS_ACCOUNT_PUBLIC_KEY > /secrets/sys_account_public_key",
            ]
          env:
            - name: OPERATOR_JWT
              value: "vault:nats-secrets/jwt/operator/myoperator#jwt"
            - name: SYS_ACCOUNT_JWT
              value: "vault:nats-secrets/jwt/operator/myoperator/account/sys#jwt"
            - name: SYS_ACCOUNT_PUBLIC_KEY
              value: "vault:nats-secrets/nkey/operator/myoperator/account/sys#publicKey"
          volumeMounts:
            - name: secrets
              mountPath: /secrets
```

That basically adds the annotations and the initContainer to the statefulSet where the nats-sever is defined.
