### ISSUE TITLE
Is websocket configurable with running NATS on K8S?

### ISSUE THREAD

**Issue by subhendukundu** [nats-io/k8s#75]
This is the best thing I found so far. :)
But is WebSocket configurable already with the current scripts?
I am not able to access `wss://ip:port`. Is there anything else I have to do apart from `curl -sSL https://nats-io.github.io/k8s/setup.sh | sh`?

I am able to run WebSocket from this example as we are adding this https://github.com/aricart/natsws-sandbox/blob/master/nats.conf
```
port: 4222
websocket: {
  port: 9222
  tls: {
    cert_file: "./certs/cert.pem"
    key_file: "./certs/key.pem"
  }
}
```

**Comment by wallyqs** [comment]
Not supported yet since has not been released, only in nightly images like `synadia/nats-server`

**Comment by sdkim81** [comment]
Is there any plan to release a websocket feature in official version?

**Comment by wallyqs** [comment]
This supported already in the nightly images so closing for now:

```yaml
nats:
  image: synadia/nats-server:nightly

websocket:
  enabled: true
  port: 443

  tls:
    secret:
      name: nats-tls
    cert: "fullchain.pem"
    key: "privkey.pem"
```
