### ISSUE TITLE
NATS Helm Chart 1.x support for k8s Service Application Protocol

### ISSUE THREAD

**Issue by theofanisM** [nats-io/k8s#761]
I recently installed istio and discovered that my applications had difficulty connecting to nats when injecting istio sidecar.

After some experimenting and chatting with @caleblloyd on Slack, we found out that we need to support [`appProtocol`](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol).

The following works

```
 ports:
  - appProtocol: tcp
    name: nats
    port: 4222
    protocol: TCP
    targetPort: nats
```
