### ISSUE TITLE
Allow annotation to be added to service via nats helm chart values.yaml

### ISSUE THREAD

**Issue by ksingh-scogo** [nats-io/k8s#784]
It would be be great to allow addition of service level annotation some thing like this

```
############################################################
# service
############################################################
service:
  enabled: true
  merge:
    annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: YourRGNameHere
    spec:
      type: LoadBalancer
      loadBalancerIP: "xx.xx.xx.xx"
```

User case : While setting up Nats on public clouds and exposing it using LoadBalancer, it make sense to have a fix public IP. Cloud providers allows to reserve Public IP and later attach these IP to loadbalancers via kubernetes service by specifying correct annotations and `LoadBalanerIP` field

Currently Nats K8s helm chart supports adding `loadBalancerIP` however it does not supports adding service level annotation

Work around : 
- Relevant section from `values.yaml`
```
############################################################
# service
############################################################
service:
  enabled: true
  merge:
    spec:
      type: LoadBalancer
      loadBalancerIP: "xx.xx.xx.xx"
```
- Create Nats cluster
```
helm upgrade --install nats nats/nats --namespace=nats --create-namespace --version 1.0.2 --values=values.yaml
```

- Manually add annotation to the service
```
kubectl annotate service -n nats nats-jetstream service.beta.kubernetes.io/azure-load-balancer-resource-group=YourAzureRG
```
