### ISSUE TITLE
Jetstream issue with fileStore disabled.

### ISSUE THREAD

**Issue by samstride** [nats-io/k8s#791]
Hi,

Thanks for maintaining the helm chart.

Running into the following issue on chart `nats-1.0.2` and app `2.9.21`

A config with `fileStore` disabled:

```yaml
config:
  cluster:
    enabled: true
    replicas: 3

  jetstream:
    enabled: true

    memoryStore:
      enabled: true
      maxSize: 128Mi

    fileStore:
      enabled: false

podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
```

Is causing the clients to throw this error:

```
nats: insufficient storage resources available
```

Things are back to normal once `filestore` is enabled.

Is this expected behaviour?
