### ISSUE TITLE
helm: support custom client certs in nats-box

### ISSUE THREAD

**Issue by wallyqs** [nats-io/k8s#80]
Make it possible to mount the certs for a sample client to test mutual TLS. something like:

```yaml
natsbox:
  enabled: true
  tls:
    insecure: false
    verify: true
    secret:
      name: nats-client-tls
    ca: "ca.crt"
    cert: "tls.crt"
    key: "tls.key"
```
