### ISSUE TITLE
No way to pass nodeSelector or Pod affinity to nats helm chart

### ISSUE THREAD

**Issue by ShubhamRasal** [nats-io/k8s#810]
### What motivated this proposal?

We have mixed node pool kubernetes cluster. We have created separate nodes for nats 
but I am unable to find the way to nats pods on those nodes.

### What is the proposed change?

- Way to add taint and toleration
- Way to pass nodeSelector and Pod affinity and anti-affinity.

**Comment by ShubhamRasal** [comment]
```
podTemplate:
  merge:
    spec:
      nodeSelector:
         xx: yy
```
