### ISSUE TITLE
Templatize apiVersion and Kind of nats/pod-monitor for GKE compatibility

### ISSUE THREAD

**Issue by pbennett** [nats-io/k8s#817]
### What motivated this proposal?

The current pod monitor spec for nats uses:
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
```
yet GKE expects:
```
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
```
See: https://cloud.google.com/stackdriver/docs/managed-prometheus/setup-managed

### What is the proposed change?

Either provide toggle for openshift vs google that switches both, or allow each to be overridden.

### Who benefits from this change?

Any users using Google Kubernetes Engine.
Managed Prometheus is now the default metrics engine for GKE clusters as well.

**Comment by caleblloyd** [comment]
It is:

```
promExporter:
  enabled: true
  podMonitor:
    enabled: true
    merge:
      apiVersion: monitoring.googleapis.com/v1
      kind: PodMonitoring
```
