### ISSUE TITLE
[Jetstream Controller] Use secrets for username/password authentication

### ISSUE THREAD

**Issue by praveenperera** [nats-io/k8s#876]
### What motivated this proposal?

I'm using username and password authentication and would like to use the controller.

### What is the proposed change?

One way I think is allowing the controller to interpolate env variables: https://github.com/nats-io/nack/issues/76#issuecomment-1995808911

And then change the deployment.yaml file to except `extraSecretMounts`. I could do the PR for this. 

### Who benefits from this change?

Anyone using username/password authentication, gitops and wants to use the jetstream controller. 

With gitops all the helm/yaml files are stored in git, so without this you would be exposing your creds.

**Comment by hhk7734** [comment]
This is an example using account.

```yaml
apiVersion: jetstream.nats.io/v1beta2
kind: Account
spec:
  name: <accountName>
  servers:
  - nats://<user>:<password>@<host>:<port>
```

```yaml
apiVersion: jetstream.nats.io/v1beta2
kind: Stream
spec:
  account: <accountName>
```
