### ISSUE TITLE
allow nats service annotations

### ISSUE THREAD

**Issue by tommyjcarpenter** [nats-io/k8s#894]
### What motivated this proposal?

we need to add an `external-dns` service annotation if `nats.service.enabled` is on, for our production setup that gives DNS names to `LoadBalancer` services. 

### What is the proposed change?

https://github.com/nats-io/k8s/blob/main/helm/charts/nats/files/service.yaml#L3

this section should include a way to specifiy service annotations

something like

```
metadata:
  {{- include "nats.metadataNamespace" $ | nindent 2 }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "nats.labels" $ | nindent 4 }}

  # NEW:
  annotations:
     {{- include "Values.service.annotations" $ | nindent 4 }}
```

### Who benefits from this change?

anybody who wants an external-dns annotation or any other service annotations. 

### What alternatives have you evaluated?

we are turning the builtin service off and instead adding our own custom service on, but this is hacky and we would like to use the builtin.

**Comment by caleblloyd** [comment]
you can merge/patch any k8s yaml right in:

```yaml
service:
  merge:
    metadata:
      annotations:
        your-annotation: here
```

Full reference of resources that support merge/patch: https://artifacthub.io/packages/helm/nats/nats#values

**Comment by tommyjcarpenter** [comment]
im having trouble with this:

```
Error: failed to parse values-stage.yaml: error converting YAML to JSON: yaml: line 46: did not find expected key
```

**Comment by tommyjcarpenter** [comment]
@caleblloyd 

with

```
# turn on the builtin service for leaf nodes
  service:
    enabled: true
    merge:
      metadata:
        annotations:
          external-dns.alpha.kubernetes.io/hostname: {{ include "nats.fullname" . }}-leaf.{{ $.Values.clusterInfo.fqdn }}
      spec:
        type: LoadBalancer
        externalTrafficPolicy: Local
```

i get

```
helm template . --name-template infra-nats --namespace infra-nats --kube-version 1.29 --values values.yaml --values values-stage.yaml

Error: failed to parse values-stage.yaml: error converting YAML to JSON: yaml: line 47: did not find expected key
```

**Comment by tommyjcarpenter** [comment]
@caleblloyd what if the value of this has to use `$.Values`? eg 

```
your-annotation: {{ $.Values...}}
```

**Comment by caleblloyd** [comment]
https://artifacthub.io/packages/helm/nats/nats#templating-values

example:

```
service:
  merge:
    metadata:
      annotations:
        your-annotation:
          $tplYaml: |
            {{ $.Values.myValue }}
```
