### ISSUE TITLE
Doc incorrect https://github.com/nats-io/k8s/tree/main/helm/charts/nack#getting-started

### ISSUE THREAD

**Issue by stand-sure** [nats-io/k8s#898]
### What version were you using?

NA

### What environment was the server running in?

NA

### Is this defect reproducible?

NA

### Given the capability you are leveraging, describe your expectation?

NA

### Given the expectation, what is the defect you are observing?

https://github.com/nats-io/k8s/tree/main/helm/charts/nack#getting-started

the example repeats `memoryStore`, viz. [comments are mine]

```yaml
natsBox:
  enabled: false

config:
  jetstream:
    enabled: true

    memoryStore:
      enabled: true
      maxSize: 256Mi

    memoryStore: # duplicate
      enabled: true
      pvc:  # not a valid subkey
        enabled: true
        size: 256Mi
```

this is probably what is wanted 

```yaml
natsBox:
  enabled: false

config:
  jetstream:
    enabled: true

    memoryStore:
      enabled: true
      maxSize: 256Mi

    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 256Mi
```
