### ISSUE TITLE
Patch args in NATS container

### ISSUE THREAD

**Issue by ypoplavs** [nats-io/k8s#906]
### What version were you using?

1.1.5 version of Helm charts

### What environment was the server running in?

GKE

### Is this defect reproducible?

yes

### Given the capability you are leveraging, describe your expectation?

Add an option to patch args in NATS container, my goal is to add DEBUG to a command. I'd like to have smth like:
```
  container:
    patch:
    - op: "replace"
      path: "/spec/template/spec/containers/0/args/-"
      value: ["--config", "/etc/nats-config/nats.conf", "-D"]
```

### Given the expectation, what is the defect you are observing?

Cannot patch args in NATS Container: https://github.com/nats-io/k8s/blob/main/helm/charts/nats/files/stateful-set/nats-container.yaml#L13

**Comment by caleblloyd** [comment]
Try:

```
  container:
    patch:
    - op: "add"
      path: "/spec/template/spec/containers/0/args/-"
      value: "-D"
```
