### ISSUE TITLE
Can't expose gateway service

### ISSUE THREAD

**Issue by boskiv** [nats-io/k8s#907]
### What version were you using?

2.10.16
helm 1.1.12

### What environment was the server running in?

k8s

### Is this defect reproducible?

yes

### Given the capability you are leveraging, describe your expectation?

-

### Given the expectation, what is the defect you are observing?

gateway port exposed in nats service

**Comment by boskiv** [comment]
```
config:
  merge:
    accounts:
      $SYS:
        users:
        - {user: admin, password: password}
      CRYPTO:
        jetstream: true
        users:
        - {user: crypto, password: password}
  promExporter:
    enabled: true
  cluster:
    enabled: true
    merge:
      name: EU
  gateway:
    enabled: true
    merge:
      name: EU
      gateways: [
        {name: US, urls: ["nats://nats-us.nats-us:7222"]},
        {name: EU, urls: ["nats://nats-eu.nats-eu:7222"]},
        {name: RU, urls: ["nats://nats-ru.nats-ru:7222"]},
      ]
  websocket:
    enabled: true
    ingress:
      enabled: true
      className: nginx
      tlsSecretName: nats-eu-ws-tls
      hosts:
      - nats-eu-ws.fra1.dev.do.spreadfighter.cloud
      merge:
        metadata:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-nginx
  jetstream:
    enabled: true
    memoryStore:
      enabled: true
      maxSize: 4Gi
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 100Gi
  service:
    ports:
      gateway:
        enabled: true
```
