### ISSUE TITLE
Unable to add annotations and additional containers by using 1.2.4 version

### ISSUE THREAD

**Issue by vijay2910** [nats-io/k8s#935]
### What motivated this proposal?

In the previous version (0.19.0), we had podAnnotations: {}, where we could disable istio injection and also had additionalContainers: [] to add extra containers like oauth2-proxy.

But from version 1.x these helm-values were removed.

### What is the proposed change?

In 1.x version please include a possible was to disable istio injection and also for adding additional containers.

### What alternatives have you evaluated?

I have tried adding these in values.yaml, but it did not work.

labels: {
    istio-injection: "disabled"    
  }

  annotations: {
    reloader.stakater.com/auto: 'true',
    sidecar.istio.io/inject: "false"
  }

**Comment by renaudhager** [comment]
Hi guys,

Do you have any updates on this? Not being able to set pod annotations is kind of a bummer.

**Comment by samuelattwood** [comment]
Just about everything in the new chart can be modified. There is a global `labels` dict if you want to apply a label to all resources, but if you want to specifically add pod labels/annotations you can do something like

```yaml
podTemplate:
  merge:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        istio-injection: "disabled"
```

**Comment by vijayreddy29** [comment]
Hello Samuel,

I added same thing as you mentioned:
merge:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
this is working.

But I'm still not able to add additional container.

**Comment by samuelattwood** [comment]
If you would like to add a container to the NATS statefulset pods you can do

```
podTemplate:
  merge:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        istio-injection: "disabled"
  patch:
  - op: add
    path: /spec/containers/-
    value:
      image: alpine:latest
      name: my-container
      args: []
```

You can add any completely separate additional resources in the `extraResources`

```yaml
extraResources:
- apiVersion: v1
  kind: Pod
  metadata:
    name: my-pod
  spec:
    containers:
    - name: alpine
      image: alpine:latest
      args: []
```
