### ISSUE TITLE
Add pod affinity for nats helm chart

### ISSUE THREAD

**Issue by LinPr** [nats-io/k8s#975]
### What motivated this proposal?

Currenty I can't find how to set pod affinity or antiAffinity for nats ,  nats usually being deployed as a cluster, it's better to schedule pod to different nodes by adding affint config in pod template, 

### What is the proposed change?

extend the helm chart configuration

### Who benefits from this change?

All of those who want to deploy nats cluster in kubernetes

**Comment by zdraganov** [comment]
Also looks like in the new version of the chart the nodeSelector is not provided as well.

**Comment by mikekuzak** [comment]
this works for me: 

```
podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
  merge:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: myorg.com/node.type
                    operator: In
                    values:
                      - "FIXED"
```
